### PR TITLE
Define Docker image.

### PR DESCRIPTION
**Pull request by jeschkies**

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
I get this error: 

```
05-04-2019 10:18:47 - commons:31 - INFO - Found 99 builds for https://jenkins.mesosphere.com/service/jenkins/job/frontend/job/dcos-ui-oss-pipeline/job/master/
05-04-2019 10:18:47 - commons:55 - INFO - Downloading 99 builds...
05-04-2019 10:18:48 - commons:43 - ERROR - Could not fetch build 725
Traceback (most recent call last):
  File "/build_stats/commons.py", line 38, in grab_test
    resp.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 942, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found'
05-04-2019 10:18:48 - commons:43 - ERROR - Could not fetch build 654
Traceback (most recent call last):
  File "/build_stats/commons.py", line 38, in grab_test
    resp.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 942, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found'
05-04-2019 10:18:49 - commons:43 - ERROR - Could not fetch build 668
Traceback (most recent call last):
  File "/build_stats/commons.py", line 38, in grab_test
    resp.raise_for_status()
```

I tried to create a new token and it didn't help. My call is:

`docker run --env AUTH='dschmidt@mesosphere.com:<token>' buildstats python build_stats/main.py https://jenkins.mesosphere.com/service/jenkins/job/frontend/job/dcos-ui-oss-pipeline/job/master/`

**Comment by jeschkies** [comment]
@DanielMSchmidt thanks for testing it. Does it not continue? The errors are misleading. It probably should just be a warning. Eg build [654](https://jenkins.mesosphere.com/service/jenkins/job/frontend/job/dcos-ui-oss-pipeline/job/master/654/) has no test results. Does it print the stats?

**Comment by DanielMSchmidt** [comment]
Yeah it ends like this:

```
iohttp.client_exceptions.ClientResponseError: 404, message='Not Found'
05-04-2019 12:10:19 - commons:57 - INFO - ...done.
                                              status  error
testsuite         testcase
plan is displayed Universe plan is displayed       2      0
Empty DataFrame
Columns: [status]
Index: []
/usr/local/lib/python3.7/site-packages/pandas/plotting/_converter.py:129: FutureWarning: Using an implicitly registered datetime converter for a matplotlib plotting method. The converter was registered by pandas on import. Future versions of pandas will require you to explicitly register matplotlib converters.

To register the converters:
	>>> from pandas.plotting import register_matplotlib_converters
	>>> register_matplotlib_converters()
  warnings.warn(msg, FutureWarning)
Traceback (most recent call last):
  File "build_stats/main.py", line 45, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "build_stats/main.py", line 42, in main
    loop.run_until_complete(analyze(user, password, job, output))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "build_stats/main.py", line 31, in analyze
    await plot(job, output)
  File "build_stats/main.py", line 23, in plot
    plt.savefig(output, format='png')
  File "/usr/local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 689, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/figure.py", line 2094, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2075, in print_figure
    **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 521, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 407, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 398, in to_filehandle
    raise ValueError('fname must be a PathLike or file handle')
ValueError: fname must be a PathLike or file handle
```

**Comment by jeschkies** [comment]
Ah, it's missing `--output=graph.png`. Hm, that should be a requirement for now. I will split up the commands for download, stats and plotting.

**Comment by DanielMSchmidt** [comment]
Ah, gotcha. It worked with that one 👍

**Review by DanielMSchmidt — APPROVED** [review]

**Pull request merged**
